---

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add Hosts to memory 
      add_host:
        name: "{{ servername }}"
        group: "{{ provisioned_vms }}

- name: Run Post Provision tasks
  hosts: {{ provisioned_vms }}
  tasks:

    - include_role: 
        name: compliance
    - include_role:
        name: satellite
    - include_role:
        name: patch

