---

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add Hosts to memory 
      add_host:
        name: "{{ servername }}"

    - name:
      include_role:
        name: compliance

    - name:
      include_role:
        name: satellite

    - name: 
      include_role:
        name: patch


